---
title: "imogen_analyses_comparisons"
author: "Imogen"
date: "2023-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up

```{r}
#!/bin/R
#PURPOSE: test different methods of differential expression analyses and compare top hits
library(readr)
library(ggpicrust2)
library(tibble)
library(tidyverse)
library(ggprism)
library(patchwork)
library(ggh4x)

#read abundance data
abundance_file <- "picrust2_out_pipeline/pathways_out/path_abun_unstrat.tsv"
abundance_data <- read_delim(abundance_file, delim = "\t", col_names = TRUE, trim_ws = TRUE) %>% as.data.frame()
#read metadata
metadata <- read_delim("../colombia/metadata_categorized_CL.txt",delim = "\t",escape_double = FALSE,trim_ws = TRUE,show_col_types = FALSE)

#isolate smoking and nonsmoking from abundance data and metadata
metadata_smoking <- filter(metadata, metadata$smoker=="Yes")
metadata_nonsmoking <- filter(metadata, metadata$smoker=="No")

abundance_data_smoking <- select(abundance_data, metadata_smoking$`#SampleID`)
abundance_data_smoking$pathway = abundance_data$pathway
abundance_data_smoking <- abundance_data_smoking %>% select(pathway, everything())

abundance_data_nonsmoking <- select(abundance_data, metadata_nonsmoking$`#SampleID`)
abundance_data_nonsmoking$pathway = abundance_data$pathway
abundance_data_nonsmoking <- abundance_data_nonsmoking %>% select(pathway, everything())
```
# Perform pathway differential abundance analysis (DAA) using LinDA
```{r}
daa_results_df_LinDA <- pathway_daa(abundance = abundance_data %>% column_to_rownames("pathway"), metadata = metadata, 
                              group = "smoker", daa_method = "LinDA", select = NULL, reference = NULL) 
daa_results_df_LinDA_smoking <- pathway_daa(abundance = abundance_data_smoking%>% column_to_rownames("pathway"), metadata = metadata_smoking, 
                                      group = "LDL_category", daa_method = "LinDA", select = NULL, reference = NULL) 
daa_results_df_LinDA_nonsmoking <- pathway_daa(abundance = abundance_data_nonsmoking %>% column_to_rownames("pathway"), metadata = metadata_nonsmoking, 
                                         group = "LDL_category", daa_method = "LinDA", select = NULL, reference = NULL)
```
# Perform pathway differential abundance analysis (DAA) using edgeR
```{r}
daa_results_df_edgeR <- pathway_daa(abundance = abundance_data %>% column_to_rownames("pathway"), metadata = metadata, 
                                    group = "smoker", daa_method = "edgeR", select = NULL, reference = NULL) 
daa_results_df_edgeR_smoking <- pathway_daa(abundance = abundance_data_smoking%>% column_to_rownames("pathway"), metadata = metadata_smoking, 
                                            group = "LDL_category", daa_method = "edgeR", select = NULL, reference = NULL) 
daa_results_df_edgeR_nonsmoking <- pathway_daa(abundance = abundance_data_nonsmoking %>% column_to_rownames("pathway"), metadata = metadata_nonsmoking, 
                                               group = "LDL_category", daa_method = "edgeR", select = NULL, reference = NULL)
```
# Perform pathway differential abundance analysis (DAA) using DESeq2
```{r}
daa_results_df_deseq <- pathway_daa(abundance = abundance_data %>% column_to_rownames("pathway"), 
                                    metadata = metadata, group = "smoker", 
                                    daa_method = "DESeq2", select = NULL, reference = NULL) 
daa_results_df_deseq_smoking <- pathway_daa(abundance = abundance_data_smoking%>% column_to_rownames("pathway"), 
                                            metadata = metadata_smoking, group = "LDL_category", 
                                            daa_method = "DESeq2", select = NULL, reference = NULL) 
daa_results_df_deseq_nonsmoking <- pathway_daa(abundance = abundance_data_nonsmoking %>% column_to_rownames("pathway"), 
                                               metadata = metadata_nonsmoking, group = "LDL_category", 
                                               daa_method = "DESeq2", select = NULL, reference = NULL)
```

### Analysis + visualisation : OVERALL SMOKING/NONSMOKING
```{r}
results <- c(daa_results_df_LinDA,daa_results_df_edgeR,daa_results_df_deseq)
sig_LinDA <- daa_results_df_LinDA%>% filter(p_values < 0.05)
sig_edgeR <- daa_results_df_edgeR%>% filter(p_values < 0.05)
sig_deseq <- daa_results_df_deseq%>% filter(p_values < 0.05)
sig_results <- rbind(sig_LinDA,sig_edgeR,sig_deseq)
unique_features <- unique(sig_results$feature)
table <- matrix(data=0,nrow=length(unique_features),ncol=3)
rownames(table) <- unique_features
colnames(table) <- c("LinDA","edgeR","DESeq2")

for (i in 1:3) {
  for (j in 1:length(unique_features)) {
    if (unique_features[j] %in% (get(paste0("sig_", c("LinDA", "edgeR", "deseq")[i])))[,1]) {
      table[j, i] <- 1}}}
library(reshape2)
binary_data <- melt(table, varnames = c("Feature", "Formula"))
binary_data$value <- as.factor(binary_data$value)  # Convert to factor

# Create a heatmap using ggplot2
ggplot(binary_data, aes(x = Formula, y = Feature, fill = value)) + geom_tile() +
  scale_fill_manual(values = c("white", "black"), labels = c(0,1)) +
  labs(x = "Method", y = "Pathway", fill = "Detection") +
  theme_minimal() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ggtitle("Differential expression: smokers vs. nonsmokers")

```

### Analysis + visualisation : SMOKING HIGH/LOW LDL
```{r}
results <- c(daa_results_df_LinDA,daa_results_df_edgeR,daa_results_df_deseq)
sig_LinDA <- daa_results_df_LinDA_nonsmoking%>% filter(p_values < 0.01)
sig_edgeR <- daa_results_df_edgeR_nonsmoking%>% filter(p_values < 0.01)
sig_deseq <- daa_results_df_deseq_nonsmoking%>% filter(p_values < 0.01)
sig_results <- rbind(sig_LinDA,sig_edgeR,sig_deseq)
unique_features <- unique(sig_results$feature)
table <- matrix(data=0,nrow=length(unique_features),ncol=3)
rownames(table) <- unique_features
colnames(table) <- c("LinDA","edgeR","DESeq2")

for (i in 1:3) {
  for (j in 1:length(unique_features)) {
    if (unique_features[j] %in% (get(paste0("sig_", c("LinDA", "edgeR", "deseq")[i])))[,1]) {
      table[j, i] <- 1}}}
library(reshape2)
binary_data <- melt(table, varnames = c("Feature", "Formula"))
binary_data$value <- as.factor(binary_data$value)  # Convert to factor

# Create a heatmap using ggplot2
ggplot(binary_data, aes(x = Formula, y = Feature, fill = value)) + geom_tile() +
  scale_fill_manual(values = c("white", "black"), labels = c(0,1)) +
  labs(x = "Method", y = "Pathway", fill = "Detection") +
  theme_minimal() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ggtitle("Differential expression: smokers high vs. low LDL")

```

