---
title: "imogen_analyses_comparisons"
author: "Imogen"
date: "2023-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up =  import packages and data

```{r}
#!/bin/R
### Install all packages
library(readr)
library(ggpicrust2)
library(tibble)
library(tidyverse)
library(ggprism)
library(patchwork)
library(ggh4x)
library(apeglm)

#read abundance data
abundance_file <- "picrust2_out_pipeline/pathways_out/path_abun_unstrat.tsv"
abundance_data <- read_delim(abundance_file, delim = "\t", col_names = TRUE, trim_ws = TRUE) %>% as.data.frame()
#read metadata
metadata <- read_delim("../colombia/metadata_categorized_CL.txt",delim = "\t",escape_double = FALSE,trim_ws = TRUE,show_col_types = FALSE)

#isolate smoking and nonsmoking from abundance data and metadata
metadata_smoking <- filter(metadata, metadata$smoker=="Yes")
metadata_nonsmoking <- filter(metadata, metadata$smoker=="No")

abundance_data_smoking <- select(abundance_data, metadata_smoking$`#SampleID`)
abundance_data_smoking$pathway = abundance_data$pathway
abundance_data_smoking <- abundance_data_smoking %>% select(pathway, everything())

abundance_data_nonsmoking <- select(abundance_data, metadata_nonsmoking$`#SampleID`)
abundance_data_nonsmoking$pathway = abundance_data$pathway
abundance_data_nonsmoking <- abundance_data_nonsmoking %>% select(pathway, everything())

### Load phyloseq object and subset according to smoker status
load("phyloseq_object_final.RData") 
phylo_smoking <-  subset_samples(phyloseq_object_final, smoker == "Yes")
phylo_nonsmoking <-  subset_samples(phyloseq_object_final, smoker == "No")
taxa_info = as.data.frame(tax_table(phylo_smoking))
taxa_info$ASV = rownames(taxa_info)

```
## Processing phyloseq object into DESeq2
```{r}
### Tidy up phyloseq object, relevel to set low LDL as baseline
phyloseq_object_final_plus1 <- transform_sample_counts(phylo_smoking, function(x) x+1)
phyloseq_object_final_deseq <- phyloseq_to_deseq2(phyloseq_object_final_plus1, ~ relevel(LDL_category, "low")) 
phyloseq_final <- DESeq(phyloseq_object_final_deseq)
res <- results(phyloseq_final, tidy=TRUE)
colnames(res)[1] = "ASV"
res_with_taxa = inner_join(taxa_info,res, by = "ASV" )

### Get significant hits
res_sig = res_with_taxa %>% filter( padj<0.01 & abs(log2FoldChange)>2)

### count and report ASVs significantly up/down reg in smokers 
upregulated_count <- sum(res_sig$log2FoldChange > 0)
downregulated_count <- sum(res_sig$log2FoldChange < 0)
cat("Number of upregulated smoking ASVs:", upregulated_count, "\n")
cat("Number of downregulated smoking ASVs:", downregulated_count, "\n")

### Order results by log2FC
res_sig <- res_sig[order(res_sig$log2FoldChange),]
#Make the plot
ggplot(data = res_sig, aes(y = reorder(Genus, -(as.numeric(log2FoldChange))), x = log2FoldChange, fill = pvalue))+
  geom_col()


```
